import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Navbar } from "~~/components/navbar";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Geist",
  description: "Generated by create turbo",
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html data-theme="light" lang="en">
      <body className={poppins.className} data-theme="light">
        <div className="flex flex-col min-h-screen max-w-screen">
          <Navbar />
          <div className="w-full flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
