name = "ens-gateway"
main = "src/index.ts"
compatibility_date = "2023-03-15"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "ens"
database_id = "a6f8e670-3858-4ae4-8e3e-71b7ce8b0a66"

# The necessary secrets are:
# - PRIVATE_KEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
