
import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Verify Wallet",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html data-theme="light" lang="en">
      <body className={poppins.className} data-theme="light">
        {children}
      </body>
    </html>
  );
}
